# Group composition for World Cup 2026
GROUPS = {
    'A': ['Mexico', 'South Africa', 'South Korea', 'Czech Republic'],
    'B': ['Canada', 'Bosnia', 'Qatar', 'Switzerland'],
    'C': ['Brazil', 'Morocco', 'Haiti', 'Scotland'],
    'D': ['USA', 'Paraguay', 'Australia', 'Turkey'],
    'E': ['Germany', 'Curacao', 'Ivory Coast', 'Ecuador'],
    'F': ['Netherlands', 'Japan', 'Sweden', 'Tunisia'],
    'G': ['Belgium', 'Egypt', 'Iran', 'New Zealand'],
    'H': ['Spain', 'Cape Verde', 'Saudi Arabia', 'Uruguay'],
    'I': ['France', 'Senegal', 'Iraq', 'Norway'],
    'J': ['Argentina', 'Algeria', 'Austria', 'Jordan'],
    'K': ['Portugal', 'Congo DR', 'Uzbekistan', 'Colombia'],
    'L': ['England', 'Croatia', 'Ghana', 'Panama'],
}

# Full list of 72 group stage matches
COPA_MATCHES = [
    {'home': 'Mexico', 'away': 'South Africa', 'group': 'A', 'date': '11/06', 'time': '16:00', 'venue': 'Azteca · Cidade do México', 'oh': 1.9, 'od': 3.4, 'oa': 3.8},
    {'home': 'South Korea', 'away': 'Czech Republic', 'group': 'A', 'date': '11/06', 'time': '23:00', 'venue': 'Estadio Akron · Guadalajara', 'oh': 2.1, 'od': 3.2, 'oa': 3.4},
    {'home': 'Czech Republic', 'away': 'South Africa', 'group': 'A', 'date': '18/06', 'time': '13:00', 'venue': 'Mercedes-Benz · Atlanta', 'oh': 2.2, 'od': 3.3, 'oa': 3.1},
    {'home': 'Mexico', 'away': 'South Korea', 'group': 'A', 'date': '18/06', 'time': '22:00', 'venue': 'Estadio Akron · Guadalajara', 'oh': 1.85, 'od': 3.5, 'oa': 4.0},
    {'home': 'Czech Republic', 'away': 'Mexico', 'group': 'A', 'date': '24/06', 'time': '22:00', 'venue': 'Azteca · Cidade do México', 'oh': 3.2, 'od': 3.2, 'oa': 2.1},
    {'home': 'South Africa', 'away': 'South Korea', 'group': 'A', 'date': '24/06', 'time': '22:00', 'venue': 'Estadio BBVA · Monterrey', 'oh': 2.8, 'od': 3.1, 'oa': 2.5},
    {'home': 'Canada', 'away': 'Bosnia', 'group': 'B', 'date': '12/06', 'time': '16:00', 'venue': 'BMO Field · Toronto', 'oh': 1.8, 'od': 3.4, 'oa': 4.2},
    {'home': 'Qatar', 'away': 'Switzerland', 'group': 'B', 'date': '13/06', 'time': '16:00', 'venue': 'Levi\\', 'oh': 3.5, 'od': 3.2, 'oa': 2.0},
    {'home': 'Switzerland', 'away': 'Bosnia', 'group': 'B', 'date': '18/06', 'time': '16:00', 'venue': 'SoFi Stadium · Los Angeles', 'oh': 1.8, 'od': 3.4, 'oa': 4.2},
    {'home': 'Canada', 'away': 'Qatar', 'group': 'B', 'date': '18/06', 'time': '19:00', 'venue': 'BC Place · Vancouver', 'oh': 1.5, 'od': 3.8, 'oa': 6.0},
    {'home': 'Switzerland', 'away': 'Canada', 'group': 'B', 'date': '24/06', 'time': '16:00', 'venue': 'BC Place · Vancouver', 'oh': 2.4, 'od': 3.2, 'oa': 2.9},
    {'home': 'Bosnia', 'away': 'Qatar', 'group': 'B', 'date': '24/06', 'time': '16:00', 'venue': 'Lumen Field · Seattle', 'oh': 1.7, 'od': 3.5, 'oa': 4.8},
    {'home': 'Brazil', 'away': 'Morocco', 'group': 'C', 'date': '13/06', 'time': '19:00', 'venue': 'MetLife · Nova York/NJ', 'oh': 1.55, 'od': 3.9, 'oa': 5.5},
    {'home': 'Haiti', 'away': 'Scotland', 'group': 'C', 'date': '13/06', 'time': '22:00', 'venue': 'Gillette Stadium · Boston', 'oh': 2.8, 'od': 3.1, 'oa': 2.5},
    {'home': 'Scotland', 'away': 'Morocco', 'group': 'C', 'date': '19/06', 'time': '19:00', 'venue': 'Gillette Stadium · Boston', 'oh': 2.6, 'od': 3.2, 'oa': 2.7},
    {'home': 'Brazil', 'away': 'Haiti', 'group': 'C', 'date': '19/06', 'time': '21:30', 'venue': 'Lincoln Financial · Philadelphia', 'oh': 1.18, 'od': 5.0, 'oa': 12.0},
    {'home': 'Scotland', 'away': 'Brazil', 'group': 'C', 'date': '24/06', 'time': '19:00', 'venue': 'Hard Rock · Miami', 'oh': 5.0, 'od': 3.8, 'oa': 1.55},
    {'home': 'Morocco', 'away': 'Haiti', 'group': 'C', 'date': '24/06', 'time': '19:00', 'venue': 'Mercedes-Benz · Atlanta', 'oh': 1.45, 'od': 4.0, 'oa': 7.0},
    {'home': 'USA', 'away': 'Paraguay', 'group': 'D', 'date': '12/06', 'time': '22:00', 'venue': 'SoFi Stadium · Los Angeles', 'oh': 1.6, 'od': 3.7, 'oa': 5.0},
    {'home': 'Australia', 'away': 'Turkey', 'group': 'D', 'date': '13/06', 'time': '01:00', 'venue': 'BC Place · Vancouver', 'oh': 2.3, 'od': 3.2, 'oa': 3.1},
    {'home': 'Turkey', 'away': 'Paraguay', 'group': 'D', 'date': '19/06', 'time': '01:00', 'venue': 'Levi\\', 'oh': 2.0, 'od': 3.3, 'oa': 3.6},
    {'home': 'USA', 'away': 'Australia', 'group': 'D', 'date': '19/06', 'time': '16:00', 'venue': 'Lumen Field · Seattle', 'oh': 1.65, 'od': 3.6, 'oa': 5.0},
    {'home': 'Turkey', 'away': 'USA', 'group': 'D', 'date': '25/06', 'time': '23:00', 'venue': 'SoFi Stadium · Los Angeles', 'oh': 3.2, 'od': 3.2, 'oa': 2.1},
    {'home': 'Paraguay', 'away': 'Australia', 'group': 'D', 'date': '25/06', 'time': '23:00', 'venue': 'Levi\\', 'oh': 2.2, 'od': 3.2, 'oa': 3.2},
    {'home': 'Germany', 'away': 'Curacao', 'group': 'E', 'date': '14/06', 'time': '14:00', 'venue': 'NRG Stadium · Houston', 'oh': 1.15, 'od': 5.5, 'oa': 15.0},
    {'home': 'Ivory Coast', 'away': 'Ecuador', 'group': 'E', 'date': '14/06', 'time': '20:00', 'venue': 'Lincoln Financial · Philadelphia', 'oh': 2.1, 'od': 3.2, 'oa': 3.5},
    {'home': 'Germany', 'away': 'Ivory Coast', 'group': 'E', 'date': '20/06', 'time': '17:00', 'venue': 'BMO Field · Toronto', 'oh': 1.55, 'od': 3.8, 'oa': 5.5},
    {'home': 'Ecuador', 'away': 'Curacao', 'group': 'E', 'date': '20/06', 'time': '21:00', 'venue': 'Arrowhead · Kansas City', 'oh': 1.4, 'od': 4.2, 'oa': 8.0},
    {'home': 'Ecuador', 'away': 'Germany', 'group': 'E', 'date': '25/06', 'time': '17:00', 'venue': 'MetLife · Nova York/NJ', 'oh': 4.5, 'od': 3.5, 'oa': 1.7},
    {'home': 'Curacao', 'away': 'Ivory Coast', 'group': 'E', 'date': '25/06', 'time': '17:00', 'venue': 'Lincoln Financial · Philadelphia', 'oh': 4.0, 'od': 3.3, 'oa': 1.85},
    {'home': 'Netherlands', 'away': 'Japan', 'group': 'F', 'date': '14/06', 'time': '17:00', 'venue': 'AT&T Stadium · Dallas', 'oh': 1.75, 'od': 3.5, 'oa': 4.5},
    {'home': 'Sweden', 'away': 'Tunisia', 'group': 'F', 'date': '14/06', 'time': '23:00', 'venue': 'Estadio BBVA · Monterrey', 'oh': 1.8, 'od': 3.4, 'oa': 4.2},
    {'home': 'Netherlands', 'away': 'Sweden', 'group': 'F', 'date': '20/06', 'time': '14:00', 'venue': 'NRG Stadium · Houston', 'oh': 1.7, 'od': 3.5, 'oa': 4.8},
    {'home': 'Tunisia', 'away': 'Japan', 'group': 'F', 'date': '20/06', 'time': '01:00', 'venue': 'Estadio BBVA · Monterrey', 'oh': 2.4, 'od': 3.2, 'oa': 2.9},
    {'home': 'Japan', 'away': 'Sweden', 'group': 'F', 'date': '25/06', 'time': '20:00', 'venue': 'AT&T Stadium · Dallas', 'oh': 2.6, 'od': 3.2, 'oa': 2.7},
    {'home': 'Tunisia', 'away': 'Netherlands', 'group': 'F', 'date': '25/06', 'time': '20:00', 'venue': 'Arrowhead · Kansas City', 'oh': 4.2, 'od': 3.3, 'oa': 1.8},
    {'home': 'Belgium', 'away': 'Egypt', 'group': 'G', 'date': '15/06', 'time': '16:00', 'venue': 'Lumen Field · Seattle', 'oh': 1.6, 'od': 3.8, 'oa': 5.5},
    {'home': 'Iran', 'away': 'New Zealand', 'group': 'G', 'date': '15/06', 'time': '22:00', 'venue': 'SoFi Stadium · Los Angeles', 'oh': 1.8, 'od': 3.5, 'oa': 4.5},
    {'home': 'Belgium', 'away': 'Iran', 'group': 'G', 'date': '21/06', 'time': '16:00', 'venue': 'SoFi Stadium · Los Angeles', 'oh': 1.55, 'od': 3.8, 'oa': 5.5},
    {'home': 'New Zealand', 'away': 'Egypt', 'group': 'G', 'date': '21/06', 'time': '22:00', 'venue': 'BC Place · Vancouver', 'oh': 2.8, 'od': 3.2, 'oa': 2.5},
    {'home': 'New Zealand', 'away': 'Belgium', 'group': 'G', 'date': '27/06', 'time': '00:00', 'venue': 'BC Place · Vancouver', 'oh': 5.5, 'od': 3.8, 'oa': 1.55},
    {'home': 'Egypt', 'away': 'Iran', 'group': 'G', 'date': '27/06', 'time': '00:00', 'venue': 'Lumen Field · Seattle', 'oh': 2.2, 'od': 3.2, 'oa': 3.2},
    {'home': 'Spain', 'away': 'Cape Verde', 'group': 'H', 'date': '15/06', 'time': '13:00', 'venue': 'Mercedes-Benz · Atlanta', 'oh': 1.3, 'od': 4.5, 'oa': 9.0},
    {'home': 'Saudi Arabia', 'away': 'Uruguay', 'group': 'H', 'date': '15/06', 'time': '19:00', 'venue': 'Hard Rock · Miami', 'oh': 3.0, 'od': 3.1, 'oa': 2.3},
    {'home': 'Spain', 'away': 'Saudi Arabia', 'group': 'H', 'date': '21/06', 'time': '13:00', 'venue': 'Mercedes-Benz · Atlanta', 'oh': 1.45, 'od': 4.0, 'oa': 7.0},
    {'home': 'Uruguay', 'away': 'Cape Verde', 'group': 'H', 'date': '21/06', 'time': '19:00', 'venue': 'Hard Rock · Miami', 'oh': 1.5, 'od': 4.0, 'oa': 7.0},
    {'home': 'Uruguay', 'away': 'Spain', 'group': 'H', 'date': '26/06', 'time': '21:00', 'venue': 'Estadio Akron · Guadalajara', 'oh': 3.8, 'od': 3.2, 'oa': 1.9},
    {'home': 'Cape Verde', 'away': 'Saudi Arabia', 'group': 'H', 'date': '26/06', 'time': '21:00', 'venue': 'NRG Stadium · Houston', 'oh': 2.5, 'od': 3.2, 'oa': 2.8},
    {'home': 'France', 'away': 'Senegal', 'group': 'I', 'date': '16/06', 'time': '16:00', 'venue': 'MetLife · Nova York/NJ', 'oh': 1.55, 'od': 3.8, 'oa': 5.5},
    {'home': 'Iraq', 'away': 'Norway', 'group': 'I', 'date': '16/06', 'time': '19:00', 'venue': 'Gillette Stadium · Boston', 'oh': 3.2, 'od': 3.1, 'oa': 2.2},
    {'home': 'France', 'away': 'Iraq', 'group': 'I', 'date': '22/06', 'time': '18:00', 'venue': 'Lincoln Financial · Philadelphia', 'oh': 1.25, 'od': 5.0, 'oa': 10.0},
    {'home': 'Norway', 'away': 'Senegal', 'group': 'I', 'date': '22/06', 'time': '21:00', 'venue': 'MetLife · Nova York/NJ', 'oh': 2.0, 'od': 3.3, 'oa': 3.6},
    {'home': 'Norway', 'away': 'France', 'group': 'I', 'date': '26/06', 'time': '16:00', 'venue': 'Gillette Stadium · Boston', 'oh': 3.8, 'od': 3.2, 'oa': 1.9},
    {'home': 'Senegal', 'away': 'Iraq', 'group': 'I', 'date': '26/06', 'time': '16:00', 'venue': 'BMO Field · Toronto', 'oh': 1.7, 'od': 3.5, 'oa': 4.8},
    {'home': 'Argentina', 'away': 'Algeria', 'group': 'J', 'date': '16/06', 'time': '22:00', 'venue': 'Arrowhead · Kansas City', 'oh': 1.4, 'od': 4.2, 'oa': 8.0},
    {'home': 'Austria', 'away': 'Jordan', 'group': 'J', 'date': '16/06', 'time': '01:00', 'venue': 'Levi\\', 'oh': 1.75, 'od': 3.5, 'oa': 4.5},
    {'home': 'Argentina', 'away': 'Austria', 'group': 'J', 'date': '22/06', 'time': '14:00', 'venue': 'AT&T Stadium · Dallas', 'oh': 1.5, 'od': 3.9, 'oa': 6.0},
    {'home': 'Jordan', 'away': 'Algeria', 'group': 'J', 'date': '22/06', 'time': '00:00', 'venue': 'Levi\\', 'oh': 2.6, 'od': 3.2, 'oa': 2.7},
    {'home': 'Jordan', 'away': 'Argentina', 'group': 'J', 'date': '27/06', 'time': '23:00', 'venue': 'AT&T Stadium · Dallas', 'oh': 7.0, 'od': 4.0, 'oa': 1.38},
    {'home': 'Algeria', 'away': 'Austria', 'group': 'J', 'date': '27/06', 'time': '23:00', 'venue': 'Arrowhead · Kansas City', 'oh': 2.4, 'od': 3.2, 'oa': 2.9},
    {'home': 'Portugal', 'away': 'Congo DR', 'group': 'K', 'date': '17/06', 'time': '14:00', 'venue': 'NRG Stadium · Houston', 'oh': 1.3, 'od': 4.5, 'oa': 9.0},
    {'home': 'Uzbekistan', 'away': 'Colombia', 'group': 'K', 'date': '17/06', 'time': '23:00', 'venue': 'Azteca · Cidade do México', 'oh': 3.8, 'od': 3.1, 'oa': 1.9},
    {'home': 'Portugal', 'away': 'Uzbekistan', 'group': 'K', 'date': '23/06', 'time': '14:00', 'venue': 'NRG Stadium · Houston', 'oh': 1.25, 'od': 5.0, 'oa': 10.0},
    {'home': 'Colombia', 'away': 'Congo DR', 'group': 'K', 'date': '23/06', 'time': '23:00', 'venue': 'Estadio Akron · Guadalajara', 'oh': 1.65, 'od': 3.6, 'oa': 5.0},
    {'home': 'Colombia', 'away': 'Portugal', 'group': 'K', 'date': '27/06', 'time': '20:30', 'venue': 'Hard Rock · Miami', 'oh': 3.8, 'od': 3.2, 'oa': 1.9},
    {'home': 'Congo DR', 'away': 'Uzbekistan', 'group': 'K', 'date': '27/06', 'time': '20:30', 'venue': 'Mercedes-Benz · Atlanta', 'oh': 1.9, 'od': 3.4, 'oa': 3.8},
    {'home': 'England', 'away': 'Croatia', 'group': 'L', 'date': '17/06', 'time': '17:00', 'venue': 'AT&T Stadium · Dallas', 'oh': 1.65, 'od': 3.6, 'oa': 5.0},
    {'home': 'Ghana', 'away': 'Panama', 'group': 'L', 'date': '17/06', 'time': '20:00', 'venue': 'BMO Field · Toronto', 'oh': 1.9, 'od': 3.4, 'oa': 3.8},
    {'home': 'England', 'away': 'Ghana', 'group': 'L', 'date': '23/06', 'time': '17:00', 'venue': 'Gillette Stadium · Boston', 'oh': 1.4, 'od': 4.2, 'oa': 8.0},
    {'home': 'Panama', 'away': 'Croatia', 'group': 'L', 'date': '23/06', 'time': '20:00', 'venue': 'BMO Field · Toronto', 'oh': 2.8, 'od': 3.1, 'oa': 2.5},
    {'home': 'Panama', 'away': 'England', 'group': 'L', 'date': '27/06', 'time': '18:00', 'venue': 'MetLife · Nova York/NJ', 'oh': 7.0, 'od': 4.0, 'oa': 1.38},
    {'home': 'Croatia', 'away': 'Ghana', 'group': 'L', 'date': '27/06', 'time': '18:00', 'venue': 'Lincoln Financial · Philadelphia', 'oh': 1.8, 'od': 3.4, 'oa': 4.2},
]